# Generated by Django 2.2.1 on 2019-06-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_teacher',
        ),
    ]
