# Generated by Django 2.2.1 on 2019-06-27 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_usermodel_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MaxLengthValidator(limit_value=10, message='用户名不能超过10个字符'), django.core.validators.MinLengthValidator(limit_value=3, message='用户名不能少于3个字符')]),
        ),
    ]
