# Generated by Django 2.2.1 on 2019-06-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190627_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='icon',
            field=models.FileField(default='images/default.jpg', upload_to=''),
        ),
    ]
