# Generated by Django 2.2.1 on 2019-06-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usermodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='icon',
            field=models.FileField(default='/images/default.jpg', upload_to=''),
        ),
    ]
