# Generated by Django 2.2.1 on 2019-06-27 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190627_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'], message='不支持的图片格式')]),
        ),
    ]
